### ISSUE TITLE
multiplayer issue

### ISSUE THREAD

**Issue by berengma** [DokimiCU/Exile#10]
game mod health, init.lua

line 320 "register_tab()" has to be commented out to allow more than one player at a time playing.

otherwise when the seconds tries to login, server crashes.

Commenting this out on the other hand makes the health tab disappear from inventory.
This makes the game impossible because information about health is vital.

**Comment by DokimiCU** [comment]
I changed it too register_tab(player) as a guess (does no harm to singleplayer, but I'm not able to test in multiplayer).

I've since seen you may have found a solution any way?

**Comment by programmerjake** [comment]
I found a way to fix it where the health tab still works: #11

**Comment by berengma** [comment]
> ( but I'm not able to test in multiplayer).
> 

That is trivial to solve :)

First run a minetest instance, chose start a new game, server yes, announce no.
Now this is your server and you are logged in as admin.

Second open a new instance of minetest. Chose join game and fill in serverip: localhost, port 30000 (default)
chose name and password and connect. Now you can test in multiplayer.

Client and server on the same machine, no problem, at least I do that in linux to test my mods in multiplayer :)

**Comment by DokimiCU** [comment]
programmerjake's fix in now in Dev branch

Thanks for tip on how to test multiplayer... I always get "connection timed out" though.

Anyway issue (should!) be fixed.
