### ISSUE TITLE
Energy drains whilist not doing anything or resting, sometimes drops to negative numbers

### ISSUE THREAD

**Issue by ghost** [DokimiCU/Exile#15]
the title says it all, possibly a bug

**Comment by berengma** [comment]
have an eye on the environment temperature. If too low or too high, energy drops. Just by doing nothing. that is intended.
Extreme temperatures drain energy. This is not a bug :)

**Comment by ghost** [comment]
> have an eye on the environment temperature. If too low or too high, energy drops. Just by doing nothing. that is intended.
> Extreme temperatures drain energy. This is not a bug :)

I'm pretty sure that 12-14°C isn't extreme, usually at that temperature energy drain stops when not moving.

**Comment by DokimiCU** [comment]
Drop to negative numbers is a known issue (it needs to be capped e.g. so 5 - 10 = 0, not -5). Minor issue which why unfixed.

Overall the health system could be improved. That's what this is about. 

Currently if you are outside Temperature Tolerance range (see clothing) it will drain energy. It will drain more if is raining etc.

But yes, it is crude - you can get hypothermia a little too easily.

**Comment by DokimiCU** [comment]
Both parts fixed/rebalanced
