### ISSUE TITLE
sound bug

### ISSUE THREAD

**Issue by berengma** [DokimiCU/Exile#20]
when one player is above surface and it is raining or snowing all other players
who are underground and should not have weather sounds at all hear a distorted sound
like a chainsaw. Only mute helps so far.

**Comment by DokimiCU** [comment]
Strange...

I think I experienced that on the server. No idea what to do about it.

I'd like the sound to slowly decrease as move underground (currently hard cut off). So this is related to a feature that needs improving anyway.
