### ISSUE TITLE
Food burns away suddenly

### ISSUE THREAD

**Issue by jeremyshannon** [DokimiCU/Exile#23]
I don't know if it's intentional, but maraka cakes and bird carcasses can transition from uncooked to cooked and then be burned up before the player can retrieve them.
 In testing this, I set up five maraka cakes on a long stove arrangement, three finished and stayed put for a while. One finished and then vanished a moment later, and one vanished instantly, before I even saw it finish cooking. In the end, about one in three cakes wound up vaporized, losing 7 out of a batch of 24.

 I've fixed this locally by removing the "flammable = 1" tag from foods that have to be cooked, but I'm unsure if that's the right solution. Perhaps the food should pass through stages, from uncooked -> cooked -> overcooked -> burnt -> destroyed, with overcooked and maybe burnt giving penalties if you try to eat it? But then again that might be too much detail.

**Comment by DokimiCU** [comment]
If food items are too hot they vaporize. (i.e. you burnt it)

Yeah, it's crude. ;-)

Cooked items are also flammable, so catch fire. (flammable = 1)

Stages is a interesting idea. I'm not particularly happy with cooking as it is.

I'll close this, as this is in fact an actual feature :-)
But you're right that this isn't great...

**Comment by jeremyshannon** [comment]
Removing the flammable tag seems to stop them from vaporizing, or at least from vaporizing the instant they're done. I didn't test what happens if you get them super hot, like with charcoal.
