### ISSUE TITLE
Development branch -> game cannot be started

### ISSUE THREAD

**Issue by berengma** [DokimiCU/Exile#24]
`ModError: Failed to load and run script from /.minetest/games/Exile/mods/health/init.lua:
/.minetest/games/Exile/mods/health/health_effects.lua:990: nesting of [[...]] is deprecated near '['
stack traceback:
	[C]: in function 'dofile'
	...minetest/games/Exile/mods/health/init.lua:36: in main chunk
Check debug.txt for details.`

This is pretty trivial to solve, but without no start possible.

**Comment by DokimiCU** [comment]
fixed
