### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by minefaco** [DokimiCU/Exile#27]
can you write a detailed guide? or maybe make it intuitive, something like goals list... with some examples for crafting furnaces and how to dig trees...

**Comment by DokimiCU** [comment]
This is on the list, I know it can be very hard for new players. I like the idea of a set of beginners achievements to work through, it does need some kind of guide to help people understand the kind of game they are playing.

However, this will likely be one of the last things to ever get added - after all major game play content exists. 

In the meantime I have a placeholder: a brief guide and tips in the readme. Maybe I could expand it a little at some point.

Thanks :-)

**Comment by DokimiCU** [comment]
Added a walkthrough (was easy enough to do). That should meet much of this need for now.
