### ISSUE TITLE
[Feature removal request] Enough with the bonging

### ISSUE THREAD

**Issue by ghost** [DokimiCU/Exile#30]
The first time I saw the "get up and walk around" message I thought "that's nice." But there's no timer. I'm lost, trying to find home and every time I sit down to regain some energy so I can walk I get this loud bong in my ears. Ouch! Please set a timer or a volume or a setting or something.

**Comment by jeremyshannon** [comment]
It has a delay between appearances, but it gets shorter as you continue to ignore it, to encourage you to stop for a few minutes. 'Cause it's not good to sit for hours at a time. That said, you can always just exit to the menu and reload, it'll be none the wiser.

 Still, I'll see about adding a setting for configuring or disabling it. Maybe the volume can be adjusted, too.
