### ISSUE TITLE
[Feature request] Better water collection

### ISSUE THREAD

**Issue by ghost** [DokimiCU/Exile#31]
I've spent so much time and so many resources trying to get my water thing fired with no luck. Can't I dig a seepage hole? Leave it to bake in the sun? Use half a coconut? If I ever find a granite boulder I'll make a mortar, can I use that?
I appreciate the hard work, but there's a level of abstraction in not only the cubic nature of the world, but the understanding of the users that needs a bit more love.

**Comment by jeremyshannon** [comment]
Seepage holes can work. Wet tiles that don't evaporate into air above them will move through sediment generally downward until it hits a rock layer and stops. Water tends to build up down there. If you cut a hole one square down into the claystone or conglomerate or what-have-you, the water can drain out one side and downward into the hole. If you place a trapdoor immediately over the hole, it will stop it from evaporating in hot weather, too. 

 You can also melt ice and snow blocks for water, though it will turn your fire to ash when it happens. Tangkal fruits are a good source of early water as well, but you gotta climb for those.
