### ISSUE TITLE
Infinite bricks

### ISSUE THREAD

**Issue by ghost** [DokimiCU/Exile#33]
I noticed you can basically get infinite bricks just from one stack of Brick And Mortar as you get 12 Brick and Mortar blocks from 8 Loose Bricks and a block of mortar. You can then lay down 8 of those BnM blocks, break them to get 8 Loose Bricks, then make 12 more BnM, lay 8 of those down, etc.

**Comment by jeremyshannon** [comment]
Fixed in my fork.
