### ISSUE TITLE
Moisture Evaporation

### ISSUE THREAD

**Issue by DanS-User** [DokimiCU/Exile#34]
Hi, in mods/nodes_nature/moisture_spread.lua
at line 48
the game is deleting the whole node instead of
transforming it from the wet version to the dry version.
Is this the reason my garden keeps sinking?
Thanks

**Comment by ghost** [comment]
Found a solution? I've been trying fixing this myself but with no luck. It's quite annoying.

**Comment by DanS-User** [comment]
> Found a solution? I've been trying fixing this myself but with no luck. It's quite annoying.

If you're asking about blocks vanishing under crops, Jeremy Shannon answered on his fork of Exile that agricultural blocks have the code to "degrade" (or vanish) if they're not completely surrounded (same level or under) by solid blocks. He also answered that line 48 refers to water blocks, not wet blocks, solving the original question.
If you need water in a dry summer in Exile 0.22, go up the mountain (+100 y- height) and use the mixing station to compact snow into ice blocks. Only ice blocks melt into water, snow blocks or slabs just vanish

**Comment by ghost** [comment]
Okay, that seems to have been the issue after all. My original farmland was sort of a 'staircase' build but since I've rebuilt it on a flat land surrounded by blocks from all sides I've been having no issues. Thank you.

**Comment by DanS-User** [comment]
> Okay, that seems to have been the issue after all. My original farmland was sort of a 'staircase' build but since I've rebuilt it on a flat land surrounded by blocks from all sides I've been having no issues. Thank you.

If you have a good garden place full of wet woodland tiles, even if it's on a slope, you shouldn't avoid it. I put slabs on the tiles at the border between higher and lower level, including diagonally. Slabs of anything, sand, silt, whatever is nearby. Wet woodland can be instantly transformed into best wet agricultural loam with a single right click. Slabs also help with moving around, no jumps. Even horizontal sticks work, if you're not a slabs fan
